import { makeStyles } from "@fluentui/react-components";

export const useStyles3 = makeStyles({
  container: {
    position: "relative",
    width: "100%",
    minHeight: "100vh",
    background: "#FFFFFF",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "20px",
  },
  logo: {
    width: "200px",
    height: "auto",
    marginBottom: "20px",
  },
  heading: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "22px",
    lineHeight: "160%",
    color: "#000000",
    marginBottom: "40px",
  },
  backButton: {
    position: "absolute",
    top: "20px",
    left: "20px",
    padding: "10px",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  backIcon: {
    width: "24px",
    height: "24px",
  },
  buttonsContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "20px",
    width: "100%",
    maxWidth: "600px",
  },
  button: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    width: "150px",
    height: "150px",
    padding: "20px",
    color: "#BD302B",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "160%",
    textAlign: "center",
    cursor: "pointer",
    transition: "background-color 0.3s",
    border: "1px solid #E0E0E0",
    boxShadow: "0px 1px 4.6px rgba(0, 0, 0, 0.15)",
    "&:hover": {
      backgroundColor: "#F5F5F5",
    },
  },
  icon: {
    marginBottom: "10px",
    width: "40px",
    height: "40px",
  },
  darkGrayIcon: {
    filter: "invert(29%) sepia(10%) saturate(0%) hue-rotate(178deg) brightness(85%) contrast(82%)", // Dark gray color filter
  },
  fontText: {
    marginTop: "10px",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "160%",
  },
});
