import { makeStyles } from "@fluentui/react-components";

export const useStyles4 = makeStyles({
  container: {
    position: "relative",
    width: "100%",
    minHeight: "100vh",
    background: "#FFFFFF",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "20px",
  },
  logo: {
    width: "200px",
    height: "auto",
    marginBottom: "20px",
  },
  heading: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "22px",
    lineHeight: "160%",
    color: "#000000",
    marginBottom: "40px",
  },
  backButton: {
    position: "absolute",
    top: "20px",
    left: "20px",
    padding: "10px",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  backIcon: {
    width: "24px",
    height: "24px",
  },
  dropdownContainer: {
    width: "100%",
    maxWidth: "600px",
    background: "#FFFFFF",
    borderRadius: "16px",
    boxShadow: "0px 1px 4.6px rgba(0, 0, 0, 0.15)",
    padding: "20px",
    marginBottom: "20px",
  },
  dropdown: {
    marginBottom: "10px",
  },
  dropdownHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid #E0E0E0",
    cursor: "pointer",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "160%",
    color: "#000000",
  },
  arrow: {
    fontSize: "12px",
  },
  dropdownList: {
    padding: "10px 0",
    background: "#FFF",
    boxShadow: "0px 1px 4.6px rgba(0, 0, 0, 0.15)",
    borderRadius: "8px",
  },
  dropdownItem: {
    padding: "5px 10px",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "160%",
    color: "#63666A",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#f0f0f0",
    },
  },
  importButton: {
    padding: "10px 20px",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    color: "#FFFFFF",
    backgroundColor: "#0081C5",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#005f99",
    },
  },
});
